fixup! Improved docker image building

diff --git a/linux/etc/buildkite-agent/hooks/command b/linux/etc/buildkite-agent/hooks/command
--- a/linux/etc/buildkite-agent/hooks/command
+++ b/linux/etc/buildkite-agent/hooks/command
@@ -77,45 +77,15 @@ volumes=(
 uid="$(id -u buildkite-builder)"
 gid="$(id -g buildkite-builder)"
 
-docker pull "${DOCKER_IMAGE}"
-timeout \
-    --kill-after="$((TIMEOUT_MINUTES + 10))m" \
-    --signal=TERM \
-    --verbose \
-    "${TIMEOUT_MINUTES}m" \
-    docker run --tty --rm \
-        --name="build-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}" \
-        --init \
-        --read-only \
-        --user="${uid}:${gid}" \
-        --cap-drop=ALL \
-        --security-opt=no-new-privileges \
-        --runtime="${DOCKER_RUNTIME:-runc}" \
-        "${volumes[@]}" \
-        --workdir=/build \
-        --entrypoint='' \
-        "${build_env[@]}" \
-        "${DOCKER_IMAGE}"  \
-        /bin/sh -e -c "${BUILDKITE_COMMAND}"
-
-# Build and push docker image using `img` from build path.
+# Build and push docker image using `img`.
+#
+# The function uses the following variables
+# * 'image_tag' is the tag of the image to push
+# * 'docker_file' path of the docker file to build relative to the
+#   repository root.
+# * 'image_context' path to the build context relative to the
+#   repository root.
 function build_docker_image() {
-    if [[ -z "${BUILD_DOCKER_IMAGE_NAME}" ]]; then
-      echo "BUILD_DOCKER_IMAGE_NAME variable is not set. Not building the docker image"
-      exit 1
-    fi
-
-    if [[ "${BUILD_DOCKER_IMAGE_NAME}" != gcr.io/opensourcecoin/* ]]; then
-      echo "Invalid BUILD_DOCKER_IMAGE_NAME. Value must start with 'gcr.io/opensourcecoin/'"
-    fi
-
-    declare img_cache_mount
-
-    declare -r image_tag="${BUILD_DOCKER_IMAGE_NAME}:${BUILDKITE_COMMIT}"
-
-    # Relative to the build directory, i.e. BUILDKITE_BUILD_CHECKOUT_PATH
-    declare -r docker_file="./img-build/Dockerfile" \
-
     # Shared cache per agent
     declare -r img_cache="img_${BUILDKITE_AGENT_NAME}_${BUILDKITE_ORGANIZATION_SLUG}_${BUILDKITE_PIPELINE_SLUG}"
     docker volume create \
@@ -137,6 +107,7 @@ function build_docker_image() {
     #
     # Don't forget to update this after new organizations are added/removed.
     # See [Note on CI and organizations].
+    declare img_cache_mount
     if [[ "${BUILDKITE_REPO}" == https://github.com/oscoin/* ||
           "${BUILDKITE_REPO}" == https://github.com/radicle-dev/* ]]
     then
@@ -184,13 +155,63 @@ function build_docker_image() {
                 --backend=native \
                 --state=/cache \
                 --output="type=docker,name=${image_tag}" \
-                . \
+                "$image_context" \
     | docker load
 
     docker push "${image_tag}"
 }
 
 
+# If the base image for the step does not exist we build it locally and
+# push it.
+if ! docker pull "${DOCKER_IMAGE}"; then
+  if [[ -n ${DOCKER_FILE:-} ]]; then
+    # Re-tag DOCKER_IMAGE with current commit
+    : "${DOCKER_IMAGE:=gcr.io/opensourcecoin/${BUILDKITE_PIPELINE_SLUG}-build}"
+    : "${DOCKER_IMAGE%%:*}"
+    : "${_%%@*}"
+    DOCKER_IMAGE="${_}:${BUILDKITE_COMMIT}"
+    declare -r image_tag="${BUILD_DOCKER_IMAGE_NAME}:${BUILDKITE_COMMIT}"
+    declare -r docker_file="$DOCKER_FILE"
+    # Context path is the directory of the docker file
+    declare image_context
+    image_context="$(realpath --relative-base="$BUILDKITE_BUILD_CHECKOUT_PATH" "$(dirname "$DOCKER_FILE")")"
+    build_docker_image
+  fi
+fi
+
+timeout \
+    --kill-after="$((TIMEOUT_MINUTES + 10))m" \
+    --signal=TERM \
+    --verbose \
+    "${TIMEOUT_MINUTES}m" \
+    docker run --tty --rm \
+        --name="build-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}" \
+        --init \
+        --read-only \
+        --user="${uid}:${gid}" \
+        --cap-drop=ALL \
+        --security-opt=no-new-privileges \
+        --runtime="${DOCKER_RUNTIME:-runc}" \
+        "${volumes[@]}" \
+        --workdir=/build \
+        --entrypoint='' \
+        "${build_env[@]}" \
+        "${DOCKER_IMAGE}"  \
+        /bin/sh -e -c "${BUILDKITE_COMMAND}"
+
 if [[ "${BUILD_DOCKER_IMAGE:-}" = "true" ]]; then
+  if [[ -z "${BUILD_DOCKER_IMAGE_NAME}" ]]; then
+    echo "BUILD_DOCKER_IMAGE_NAME variable is not set. Not building the docker image"
+    exit 1
+  fi
+
+  if [[ "${BUILD_DOCKER_IMAGE_NAME}" != gcr.io/opensourcecoin/* ]]; then
+    echo "Invalid BUILD_DOCKER_IMAGE_NAME. Value must start with 'gcr.io/opensourcecoin/'"
+  fi
+
+  image_tag="${BUILD_DOCKER_IMAGE_NAME}:${BUILDKITE_COMMIT}" \
+  docker_file="./img-build/Dockerfile" \
+  image_context="./"
   build_docker_image
 fi
